# Sentiment Analysis with an RNN

In this notebook, you'll implement a recurrent neural network that performs sentiment analysis. 
>Using an RNN rather than a strictly feedforward network is more accurate since we can include information about the *sequence* of words. 

Here we'll use a dataset of movie reviews, accompanied by sentiment labels: positive or negative.

<img src="assets/reviews_ex.png" width=40%>

### Network Architecture

The architecture for this network is shown below.

<img src="assets/network_diagram.png" width=40%>

>**First, we'll pass in words to an embedding layer.** We need an embedding layer because we have tens of thousands of words, so we'll need a more efficient representation for our input data than one-hot encoded vectors. You should have seen this before from the Word2Vec lesson. You can actually train an embedding with the Skip-gram Word2Vec model and use those embeddings as input, here. However, it's good enough to just have an embedding layer and let the network learn a different embedding table on its own. *In this case, the embedding layer is for dimensionality reduction, rather than for learning semantic representations.*

>**After input words are passed to an embedding layer, the new embeddings will be passed to LSTM cells.** The LSTM cells will add *recurrent* connections to the network and give us the ability to include information about the *sequence* of words in the movie review data. 

>**Finally, the LSTM outputs will go to a sigmoid output layer.** We're using a sigmoid function because positive and negative = 1 and 0, respectively, and a sigmoid will output predicted, sentiment values between 0-1. 

We don't care about the sigmoid outputs except for the **very last one**; we can ignore the rest. We'll calculate the loss by comparing the output at the last time step and the training label (pos or neg).

#### Load in and Visualize the data

In [ ]:
import numpy as np

# read data from text files
with open('data/reviews.txt', 'r') as f:
    reviews = f.read()

with open('data/labels.txt', 'r') as f:
    labels = f.read()

In [ ]:
print(reviews[:2000])
print()
print(labels[:20])

bromwell high is a cartoon comedy . it ran at the same time as some other programs about school life  such as  teachers  . my   years in the teaching profession lead me to believe that bromwell high  s satire is much closer to reality than is  teachers  . the scramble to survive financially  the insightful students who can see right through their pathetic teachers  pomp  the pettiness of the whole situation  all remind me of the schools i knew and their students . when i saw the episode in which a student repeatedly tried to burn down the school  i immediately recalled . . . . . . . . . at . . . . . . . . . . high . a classic line inspector i  m here to sack one of your teachers . student welcome to bromwell high . i expect that many adults of my age think that bromwell high is far fetched . what a pity that it isn  t   
story of a man who has unnatural feelings for a pig . starts out with a opening scene that is a terrific example of absurd comedy . a formal orchestra audience is turn

## Data pre-processing

The first step when building a neural network model is getting your data into the proper form to feed into the network. Since we're using embedding layers, we'll need to encode each word with an integer. We'll also want to clean it up a bit.

You can see an example of the reviews data above. Here are the processing steps, we'll want to take:
>* We'll want to get rid of periods and extraneous punctuation.
* Also, you might notice that the reviews are delimited with newline characters `\n`. To deal with those, I'm going to split the text into each review using `\n` as the delimiter. 
* Then I can combined all the reviews back together into one big string.

First, let's remove all punctuation. Then get all the text without the newlines and split it into individual words.

In [ ]:
from string import punctuation
print(punctuation)

reviews = reviews.lower()
all_text = ''.join([c for c in reviews if c not in punctuation])

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [ ]:
# split by new lines because we assume next line will be next reviews
reviews_split = all_text.split('\n')
all_text = ' '.join(reviews_split)

# create the list of the words
words = all_text.split()

In [ ]:
words[:30]

['bromwell',
 'high',
 'is',
 'a',
 'cartoon',
 'comedy',
 'it',
 'ran',
 'at',
 'the',
 'same',
 'time',
 'as',
 'some',
 'other',
 'programs',
 'about',
 'school',
 'life',
 'such',
 'as',
 'teachers',
 'my',
 'years',
 'in',
 'the',
 'teaching',
 'profession',
 'lead',
 'me']

### Encoding the words

The embedding lookup requires that we pass in integers to our network. The easiest way to do this is to create dictionaries that map the words in the vocabulary to integers. Then we can convert each of our reviews into integers so they can be passed into the network.

> **Exercise:** Now you're going to encode the words with integers. Build a dictionary that maps words to integers. Later we're going to pad our input vectors with zeros, so make sure the integers **start at 1, not 0**.
> Also, convert the reviews to integers and store the reviews in a new list called `reviews_ints`.

In [ ]:
from collections import Counter

# It return dictionry 
counts = Counter(words)

# It return keys in decending order value associate
vocab = sorted(counts, key=counts.get, reverse=True)
# counts.most_common()
vocab_to_int = {word: ii for ii, word in enumerate(vocab, 1)}

# Tokenize each review to review_split
# store the tokenize reviews into the reviews_ints
reviews_ints = []
for review in reviews_split:
    reviews_ints.append([vocab_to_int[word] for word in review.split()])  # we are getting only numbers and appending into the list 


**Test your code**

As a text that you've implemented the dictionary correctly, print out the number of unique words in your vocabulary and the contents of the first, tokenized review.

## What is tokenzation?:  Simply `each word converted into the integer`

In [ ]:
# stats about vocabulary
print('Unique words: ', len((vocab_to_int)))  # should ~ 74000+
print()

# print tokens in first review
print('Tokenized review: \n', reviews_ints[:1])

Unique words:  74072

Tokenized review: 
 [[21025, 308, 6, 3, 1050, 207, 8, 2138, 32, 1, 171, 57, 15, 49, 81, 5785, 44, 382, 110, 140, 15, 5194, 60, 154, 9, 1, 4975, 5852, 475, 71, 5, 260, 12, 21025, 308, 13, 1978, 6, 74, 2395, 5, 613, 73, 6, 5194, 1, 24103, 5, 1983, 10166, 1, 5786, 1499, 36, 51, 66, 204, 145, 67, 1199, 5194, 19869, 1, 37442, 4, 1, 221, 883, 31, 2988, 71, 4, 1, 5787, 10, 686, 2, 67, 1499, 54, 10, 216, 1, 383, 9, 62, 3, 1406, 3686, 783, 5, 3483, 180, 1, 382, 10, 1212, 13583, 32, 308, 3, 349, 341, 2913, 10, 143, 127, 5, 7690, 30, 4, 129, 5194, 1406, 2326, 5, 21025, 308, 10, 528, 12, 109, 1448, 4, 60, 543, 102, 12, 21025, 308, 6, 227, 4146, 48, 3, 2211, 12, 8, 215, 23]]


### Encoding the labels

Our labels are "positive" or "negative". To use these labels in our network, we need to convert them to 0 and 1.

> **Exercise:** Convert labels from **`positive` and `negative` to 1 and 0**, respectively, and place those in a new list, `encoded_labels`.

In [ ]:
# 1=positive, 0=negative label conversion
labels_split = labels.split('\n')
encoded_labels = np.array([1 if label == 'positive' else 0 for label in labels_split])

### Removing Outliers

As an additional pre-processing step, we want to make sure that our reviews are in good shape for standard processing. That is, our network will expect a standard input text size, and so, we'll want to shape our reviews into a specific length. We'll approach this task in two main steps:

1. Getting rid of extremely long or short reviews; the outliers
2. Padding/truncating the remaining data so that we have reviews of the same length.

<img src="assets/outliers_padding_ex.png" width=40%>

Before we pad our review text, we should check for reviews of extremely short or long lengths; outliers that may mess with our training.

In [ ]:
# Outlier review stats
reviews_lengths = Counter([len(i) for i in reviews_ints])
print('Zero length reviews KEYS: {}'.format(reviews_lengths[0]))
print('Maximum length reviews KEYS: {}'.format(max(reviews_lengths)))

Zero length reviews KEYS: 1
Maximum length reviews KEYS: 2514


Okay, a couple issues here. We seem to have one review with zero length. And, the maximum review length is way too many steps for our RNN. We'll have to remove any super short reviews and truncate super long reviews. This removes outliers and should allow our model to train more efficiently.

> **Exercise:** First, remove *any* reviews with zero length from the `reviews_ints` list and their corresponding label in `encoded_labels`.

In [ ]:
print('Number of reviews before removing outliers: ', len(reviews_ints))

## remove any reviews/labels with zero length from the reviews_ints list.
non_zero_idx = [idx for idx, word in enumerate(reviews_ints) if len(word)!=0]

# Removing the 0 with indices
reviews_ints = [reviews_ints[i] for i in non_zero_idx]
encoded_labels = [encoded_labels[i] for i in non_zero_idx]

print('Number of reviews after removing outliers: ', len(reviews_ints))

Number of reviews before removing outliers:  25001
Number of reviews after removing outliers:  25000


---
## Padding sequences

To deal with both short and very long reviews, we'll pad or truncate all our reviews to a specific length. For reviews shorter than some `seq_length`, we'll pad with 0s. For reviews longer than `seq_length`, we can truncate them to the first `seq_length` words. A good `seq_length`, in this case, is 200.

> **Exercise:** Define a function that returns an array `features` that contains the padded data, of a standard size, that we'll pass to the network. 
* The data should come from `review_ints`, since we want to feed integers to the network. 
* Each row should be `seq_length` elements long. 
* For reviews shorter than `seq_length` words, **left pad** with 0s. That is, if the review is `['best', 'movie', 'ever']`, `[117, 18, 128]` as integers, the row will look like `[0, 0, 0, ..., 0, 117, 18, 128]`. 
* For reviews longer than `seq_length`, use only the first `seq_length` words as the feature vector.

As a small example, if the `seq_length=10` and an input review is: 
```
[117, 18, 128]
```
The resultant, padded sequence should be: 

```
[0, 0, 0, 0, 0, 0, 0, 117, 18, 128]
```

**Your final `features` array should be a 2D array, with as many rows as there are reviews, and as many columns as the specified `seq_length`.**

This isn't trivial and there are a bunch of ways to do this. But, if you're going to be building your own deep learning networks, you're going to have to get used to preparing your data.

In [ ]:
print(reviews_ints[:2])

[[21025, 308, 6, 3, 1050, 207, 8, 2138, 32, 1, 171, 57, 15, 49, 81, 5785, 44, 382, 110, 140, 15, 5194, 60, 154, 9, 1, 4975, 5852, 475, 71, 5, 260, 12, 21025, 308, 13, 1978, 6, 74, 2395, 5, 613, 73, 6, 5194, 1, 24103, 5, 1983, 10166, 1, 5786, 1499, 36, 51, 66, 204, 145, 67, 1199, 5194, 19869, 1, 37442, 4, 1, 221, 883, 31, 2988, 71, 4, 1, 5787, 10, 686, 2, 67, 1499, 54, 10, 216, 1, 383, 9, 62, 3, 1406, 3686, 783, 5, 3483, 180, 1, 382, 10, 1212, 13583, 32, 308, 3, 349, 341, 2913, 10, 143, 127, 5, 7690, 30, 4, 129, 5194, 1406, 2326, 5, 21025, 308, 10, 528, 12, 109, 1448, 4, 60, 543, 102, 12, 21025, 308, 6, 227, 4146, 48, 3, 2211, 12, 8, 215, 23], [63, 4, 3, 125, 36, 47, 7472, 1395, 16, 3, 4181, 505, 45, 17, 3, 622, 134, 12, 6, 3, 1279, 457, 4, 1721, 207, 3, 10624, 7373, 300, 6, 667, 83, 35, 2116, 1086, 2989, 34, 1, 898, 46417, 4, 8, 13, 5096, 464, 8, 2656, 1721, 1, 221, 57, 17, 58, 794, 1297, 832, 228, 8, 43, 98, 123, 1469, 59, 147, 38, 1, 963, 142, 29, 667, 123, 1, 13584, 410, 61, 94, 177

In [ ]:
def pad_features(reviews_ints, seq_length):
    ''' Return features of review_ints, where each review is padded with 0's 
        or truncated to the input seq_length.
    '''
    
    # getting the correct rows x cols shape
    features = np.zeros((len(reviews_ints), seq_length), dtype=np.int64)

    # for each review, I grab that review and 
    for i, row in enumerate(reviews_ints):
        features[i, -len(row):] = np.array(row)[:seq_length]
    
    return features

In [ ]:
# Test your implementation!

seq_length = 200

features = pad_features(reviews_ints, seq_length=seq_length)

## test statements - do not change - ##
assert len(features)==len(reviews_ints), "Your features should have as many rows as reviews."
assert len(features[0])==seq_length, "Each feature row should contain seq_length values."

# print first 10 values of the first 30 batches 
print(features[:30,:10])

[[    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [22382    42 46418    15   706 17139  3389    47    77    35]
 [ 4505   505    15     3  3342   162  8312  1652     6  4819]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [   54    10    14   116    60   798   552    71   364     5]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    1   330   578    34     3   162   748  2731     9   325]
 [    9    11 10171  5305  1946   689   444    22   280   673]
 [    0     0     0     0     0     0     0     0     0

## Training, Validation, Test

With our data in nice shape, we'll split it into training, validation, and test sets.

> **Exercise:** Create the training, validation, and test sets. 
* You'll need to create sets for the features and the labels, `train_x` and `train_y`, for example. 
* Define a split fraction, `split_frac` as the fraction of data to **keep** in the training set. Usually this is set to 0.8 or 0.9. 
* Whatever data is left will be split in half to create the validation and *testing* data.

In [ ]:
split_frac = 0.8

## split data into training, validation, and test data (features and labels, x and y)

split_idx = int(len(features)*split_frac)
train_x, remaining_x = features[:split_idx], features[split_idx:]
train_y, remaining_y = encoded_labels[:split_idx], encoded_labels[split_idx:]

test_idx = int(len(remaining_x)*0.5)
val_x, test_x = remaining_x[:test_idx], remaining_x[test_idx:]
val_y, test_y = remaining_y[:test_idx], remaining_y[test_idx:]

## print out the shapes of your resultant feature data
print("\t\t\tFeature Shapes:")
print("Train set: \t\t{}".format(train_x.shape), 
      "\nValidation set: \t{}".format(val_x.shape),
      "\nTest set: \t\t{}".format(test_x.shape))

			Feature Shapes:
Train set: 		(20000, 200) 
Validation set: 	(2500, 200) 
Test set: 		(2500, 200)


**Check your work**

With train, validation, and test fractions equal to 0.8, 0.1, 0.1, respectively, the final, feature data shapes should look like:
```
                    Feature Shapes:
Train set: 		 (20000, 200) 
Validation set: 	(2500, 200) 
Test set: 		  (2500, 200)
```

---
## DataLoaders and Batching

After creating training, test, and validation data, we can create DataLoaders for this data by following two steps:
1. Create a known format for accessing our data, using [TensorDataset](https://pytorch.org/docs/stable/data.html#) which takes in an input set of data and a target set of data with the same first dimension, and creates a dataset.
2. Create DataLoaders and batch our training, validation, and test Tensor datasets.

```
train_data = TensorDataset(torch.from_numpy(train_x), torch.from_numpy(train_y))
train_loader = DataLoader(train_data, shuffle=True, batch_size=batch_size)
```

This is an alternative to creating a generator function for batching our data into full batches.

In [ ]:
type(train_x)

numpy.ndarray

In [ ]:
import torch
from torch.utils.data import TensorDataset, DataLoader


# create Tensor datasets
# Remember we faced difficulties while making train_data soln in forum (np.asarray(x))

train_data = TensorDataset(torch.from_numpy(np.asarray(train_x)), torch.from_numpy(np.asarray(train_y)))
valid_data = TensorDataset(torch.from_numpy(np.asarray(val_x)), torch.from_numpy(np.asarray(val_y)))
test_data = TensorDataset(torch.from_numpy(np.asarray(test_x)), torch.from_numpy(np.asarray(test_y)))

# dataloaders
batch_size = 50

# make sure to SHUFFLE your data
train_loader = DataLoader(train_data, shuffle=True, batch_size=batch_size)
valid_loader = DataLoader(valid_data, shuffle=True, batch_size=batch_size)
test_loader = DataLoader(test_data, shuffle=True, batch_size=batch_size)

In [ ]:
# obtain one batch of training data
dataiter = iter(train_loader)
sample_x, sample_y = dataiter.next()

print('Sample input size: ', sample_x.size()) # batch_size, seq_length
print('Sample input: \n', sample_x)
print()
print('Sample label size: ', sample_y.size()) # batch_size
print('Sample label: \n', sample_y)

Sample input size:  torch.Size([50, 200])
Sample input: 
 tensor([[    0,     0,     0,  ...,  1401,   434,  1521],
        [    0,     0,     0,  ...,  1713,    23, 36558],
        [    0,     0,     0,  ...,    29,     3,    18],
        ...,
        [   11,    18,   483,  ...,   215,    23,   774],
        [   10,  1805,   379,  ...,   145,   117,     9],
        [   10,   216,    11,  ...,    80,    48,     6]])

Sample label size:  torch.Size([50])
Sample label: 
 tensor([1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
        1, 1])


---
# Sentiment Network with PyTorch

Below is where you'll define the network.

<img src="assets/network_diagram.png" width=40%>

The layers are as follows:
1. An [embedding layer](https://pytorch.org/docs/stable/nn.html#embedding) that converts our word tokens (integers) into embeddings of a specific size.
2. An [LSTM layer](https://pytorch.org/docs/stable/nn.html#lstm) defined by a hidden_state size and number of layers
3. A fully-connected output layer that maps the LSTM layer outputs to a desired output_size
4. A sigmoid activation layer which turns all outputs into a value 0-1; return **only the last sigmoid output** as the output of this network.

### The Embedding Layer

We need to add an [embedding layer](https://pytorch.org/docs/stable/nn.html#embedding) because there are 74000+ words in our vocabulary. It is massively inefficient to one-hot encode that many classes. So, instead of one-hot encoding, we can have an embedding layer and use that layer as a lookup table. You could train an embedding layer using Word2Vec, then load it here. But, it's fine to just make a new layer, using it for only dimensionality reduction, and let the network learn the weights.


### The LSTM Layer(s)

We'll create an [LSTM](https://pytorch.org/docs/stable/nn.html#lstm) to use in our recurrent network, which takes in an input_size, a hidden_dim, a number of layers, a dropout probability (for dropout between multiple layers), and a batch_first parameter.

Most of the time, your network will have better performance with more layers; between 2-3. Adding more layers allows the network to learn really complex relationships. 

> **Exercise:** Complete the `__init__`, `forward`, and `init_hidden` functions for the SentimentRNN model class.

Note: `init_hidden` should initialize the hidden and cell state of an lstm layer to all zeros, and move those state to GPU, if available.

In [ ]:
# First checking if GPU is available
train_on_gpu = torch.cuda.is_available()

if (train_on_gpu):
    print("Traning on the GPU")
else:
    print("No GPU available, Traning on the CPU")

Traning on the GPU


In [ ]:
from torch import nn

class SentimentRNN(nn.Module):
    def __init__(self, vocab_size, output_size, embedding_dim, hidden_dim, n_layers, drop_prob = 0.5):
        """
        Initializing the model by setting up the layers.
        
        """
        super(SentimentRNN, self).__init__()
        
        self.ouptut_size = output_size
        self.n_layers = n_layers
        self.hidden_dim = hidden_dim
        self.vocab_size = vocab_size
        self.embedding_dim = embedding_dim
        self.drop_prob = drop_prob
        
        # define all layers
        
        # Define the embedding layer
        self.embeddings = nn.Embedding(vocab_size, embedding_dim)
        
        ## TODO: define the LSTM
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, n_layers, dropout = drop_prob, batch_first = True)
        
        # Define Dropout layer
        self.dropout = nn.Dropout(0.3)
        
        # Define the Linear and fully connected layer
        self.fc = nn.Linear(hidden_dim, output_size)
        
        # Define the sigmoid function to apply at the last
        self.sig = nn.Sigmoid()
        
        
    def forward(self, x, hidden):
        """
        Perform the forward pass of our model on some input and hidden states
        """
        
        batch_size = x.shape[0]
        
        # pass data to the embedding layer
        x = self.embeddings(x)
        
        # pass data to the LSTM layer
        output, hidden = self.lstm(x, hidden)
        
        # dropout prevent overfitting the data
        output = self.dropout(output)
        
        # Flatten the before pass the linear layer
        output = output.contiguous().view(-1, self.hidden_dim)
        
        # Finally, pass to the fully connected layer
        output = self.fc(output)
        
        # Apply the sigmoid
        sig_out = self.sig(output)
        
        # get the last batch of the output(labels) according to the above architecture for sentiment analysis.
        sig_out = sig_out.view(batch_size, -1)  # reshape batch_size first
        sig_out = sig_out[:, -1]  
        
        # return the last sigmoid and hidden state
        return sig_out, hidden
    
    def init_hidden(self, batch_size):
        """ Initialize the hidden state """
        # Create two new tensors with sizes n_layers x batch_size x hidden_dim,
        # initialized to zero, for hidden state and cell state of LSTM.
        weight = next(self.parameters()).data
        
        if train_on_gpu:
            hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda(),
                     weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda())
        else:
            hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_(),
                     weight.new(self.n_layers, batch_size, self.hidden_dim).zero_())
        
        return hidden
    
        

## Instantiate the network

Here, we'll instantiate the network. First up, defining the hyperparameters.

* `vocab_size`: Size of our vocabulary or the range of values for our input, word tokens.
* `output_size`: Size of our desired output; the number of class scores we want to output (pos/neg).
* `embedding_dim`: Number of columns in the embedding lookup table; size of our embeddings.
* `hidden_dim`: Number of units in the hidden layers of our LSTM cells. Usually larger is better performance wise. Common values are 128, 256, 512, etc.
* `n_layers`: Number of LSTM layers in the network. Typically between 1-3

> **Exercise:** Define the model  hyperparameters.


In [ ]:
# Instantiate the model w/ hyperparams
vocab_size = len(vocab_to_int) + 1  # +1 for the 0 padding + our word tokens
output_size = 1
embedding_dim = 400
hidden_dim = 256
n_layers = 2

net = SentimentRNN(vocab_size, output_size, embedding_dim, hidden_dim, n_layers)

print(net)

SentimentRNN(
  (embeddings): Embedding(74073, 400)
  (lstm): LSTM(400, 256, num_layers=2, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.3, inplace=False)
  (fc): Linear(in_features=256, out_features=1, bias=True)
  (sig): Sigmoid()
)


---
## Training

Below is the typical training code. If you want to do this yourself, feel free to delete all this code and implement it yourself. You can also add code to save a model by name.

>We'll also be using a new kind of cross entropy loss, which is designed to work with a single Sigmoid output. [BCELoss](https://pytorch.org/docs/stable/nn.html#bceloss), or **Binary Cross Entropy Loss**, applies cross entropy loss to a single value between 0 and 1.

We also have some data and training hyparameters:

* `lr`: Learning rate for our optimizer.
* `epochs`: Number of times to iterate through the training dataset.
* `clip`: The maximum gradient value to clip at (to prevent exploding gradients).

In [ ]:
from torch import optim

In [ ]:
# loss and optimization functions
lr = 0.001

criterion = nn.BCELoss()
optimizer = optim.Adam(net.parameters(), lr = lr)

In [ ]:
# training the program
import time

start = time.time()

epochs = 3  # I noticed, after 4 epoch validation loss start increasing 

counter = 0
print_every = 100
clip = 5 # Clipping the gradient

# Move to the GPU, if available
if train_on_gpu:
    net.cuda()

net.train()
# Train for the some number of epoch
for epoch in range(epochs):
    # initialize the hidden state
    hidden = net.init_hidden(batch_size)

    # Batch loop
    for inputs, labels in train_loader:
        counter += 1

        if train_on_gpu:
            inputs, labels = inputs.cuda(), labels.cuda()

        # Creating the new vaariable for hidden state, otherwise
        # we'd backprop throgh entire training history
        hidden = tuple([each.data for each in hidden])

        # Zero accumulated gradient
        net.zero_grad()

        # Get the output from the model
        output, hidden = net(inputs, hidden)

        # Calculate the loss and perform backprop
        loss = criterion(output.squeeze(), labels.float())
        loss.backward()

        # 'clip_grad_norm' helps prevent exploding the gradient problem in RNNs / LSTMs
        nn.utils.clip_grad_norm(net.parameters(), clip)
        optimizer.step()

        # Loss stats:
        if counter % print_every == 0:
            # Get validation loss
            val_hidden = net.init_hidden(batch_size)
            val_losses = []
            net.eval()

            for inputs, labels in valid_loader:

                # move to the gpu
                if train_on_gpu:
                    inputs, labels = inputs.cuda(), labels.cuda()

                val_hidden = tuple([each.data for each in val_hidden])

                # Pass the data to the model
                output, val_hidden = net(inputs, val_hidden)
                # Compute the loss
                loss = criterion(output.squeeze(), labels.float())
                val_losses.append(loss.item())

            net.train()  # back to the training mode after iterating throught he validation

            print('Epoch: {}/{}'.format(epoch+1, epochs),
                  'Step: {}...'.format(counter),
                  'Tranining Loss: {:.6f}'.format(loss.item()),
                  'Validation Loss: {:.6f}'.format(np.mean(val_losses)))

end = time.time()
print("Tranning time {:5f}.....".format(end-start))
                

/tmp/ipykernel_98/3233794646.py:44: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  nn.utils.clip_grad_norm(net.parameters(), clip)


Epoch: 1/3 Step: 100... Tranining Loss: 0.693368 Validation Loss: 0.628374
Epoch: 1/3 Step: 200... Tranining Loss: 0.624657 Validation Loss: 0.645239
Epoch: 1/3 Step: 300... Tranining Loss: 0.697585 Validation Loss: 0.722950
Epoch: 1/3 Step: 400... Tranining Loss: 0.545560 Validation Loss: 0.547032
Epoch: 2/3 Step: 500... Tranining Loss: 0.541139 Validation Loss: 0.482640
Epoch: 2/3 Step: 600... Tranining Loss: 0.572084 Validation Loss: 0.478795
Epoch: 2/3 Step: 700... Tranining Loss: 0.437389 Validation Loss: 0.474145
Epoch: 2/3 Step: 800... Tranining Loss: 0.457353 Validation Loss: 0.448190
Epoch: 3/3 Step: 900... Tranining Loss: 0.398582 Validation Loss: 0.480708
Epoch: 3/3 Step: 1000... Tranining Loss: 0.471892 Validation Loss: 0.446289
Epoch: 3/3 Step: 1100... Tranining Loss: 0.470503 Validation Loss: 0.448442
Epoch: 3/3 Step: 1200... Tranining Loss: 0.747651 Validation Loss: 0.448629
Tranning time 144.921918.....


---
## Testing

There are a few ways to test your network.

* **Test data performance:** First, we'll see how our trained model performs on all of our defined test_data, above. We'll calculate the average loss and accuracy over the test data.

* **Inference on user-generated data:** Second, we'll see if we can input just one example review at a time (without a label), and see what the trained model predicts. Looking at new, user input data like this, and predicting an output label, is called **inference**.

#### We can save the model but I'm skipping here 

In [ ]:
# Get test data loss and accuracy

test_losses = []
num_correct = 0

# init hidden state
hidden = net.init_hidden(batch_size)

net.eval()
# Iterate over the test data
for inputs, labels in test_loader:
    # Go over the hidden state that we initialized
    hidden = tuple([each.data for each in hidden])
    
    # Move to the GPU
    if train_on_gpu:
        inputs, labels = inputs.cuda(), labels.cuda()
    
    # pass data to the model
    output, hidden = net(inputs, hidden)
    
    # Calculate the loss
    loss = criterion(output.squeeze(), labels.float())
    test_losses.append(loss.item())
    
    # convert output probabilities to predicted class (0 or 1)
    pred = torch.round(output.squeeze())  # rouding the nearest integer
    
    # Compare prediction to the true labels
    correct_tensor = pred.eq(labels.float().view_as(pred))
    # Shift to the cpu
    correct = np.squeeze(correct_tensor.numpy()) if not train_on_gpu else np.squeeze(correct_tensor.cpu().numpy())
    num_correct += np.sum(correct)
    
#-----stats!----#
# Average test loss
print("Average Test Loss:  {:.3f}".format(np.mean(test_losses)))

# Accuracy over all test data
test_accu = num_correct/len(test_loader.dataset)
print("Test accuracy: {:.3f}".format(test_accu))
    

Average Test Loss:  0.446
Test accuracy: 0.793


### Inference on a test review

You can change this test_review to any text that you want. Read it and think: is it pos or neg? Then see if your model predicts correctly!
    
> **Exercise:** Write a `predict` function that takes in a trained net, a plain text_review, and a sequence length, and prints out a custom statement for a positive or negative review!
* You can use any functions that you've already defined or define any helper functions you want to complete `predict`, but it should just take in a trained net, a text review, and a sequence length.


In [ ]:
# negative test review
test_review_neg = 'The worst movie I have seen; acting was terrible and I want my money back. This movie had bad acting and the dialogue was slow.'


In [ ]:
from string import punctuation

def tokenize(review):
    reviews = review.lower()
    all_text = ''.join([c for c in reviews if c not in punctuation])
    
    words = all_text.split()
    
    reviews_ints = []
    
    reviews_ints.append([vocab_to_int[word] for word in words])  # we are getting only numbers and appending into the list 
        
    return reviews_ints


In [ ]:
tokenize(test_review_neg)

[[1,
  247,
  18,
  10,
  28,
  108,
  113,
  14,
  388,
  2,
  10,
  181,
  60,
  273,
  144,
  11,
  18,
  68,
  76,
  113,
  2,
  1,
  410,
  14,
  539]]

In [ ]:
# from string import punctuation

# def tokenize_review(test_review):
#     test_review = test_review.lower() # lowercase
#     # get rid of punctuation
#     test_text = ''.join([c for c in test_review if c not in punctuation])

#     # splitting by spaces
#     test_words = test_text.split()

#     # tokens
#     test_ints = []
#     test_ints.append([vocab_to_int[word] for word in test_words])

#     return test_ints

In [ ]:
# def predict(net, test_review, sequence_length=200):

#     net.eval()

#     # tokenize review
#     test_ints = tokenation_review(test_review)

#     # pad tokenized sequence
#     seq_length=sequence_length
#     features = pad_features(test_ints, seq_length)

#     # convert to tensor to pass into your model
#     feature_tensor = torch.from_numpy(features)

#     batch_size = feature_tensor.size(0)

#     # initialize hidden state
#     h = net.init_hidden(batch_size)

#     if(train_on_gpu):
#         feature_tensor = feature_tensor.cuda()

#     # get the output from the model
#     output, h = net(feature_tensor, h)

#     # convert output probabilities to predicted class (0 or 1)
#     pred = torch.round(output.squeeze()) 
#     # printing output value, before rounding
#     print('Prediction value, pre-rounding: {:.6f}'.format(output.item()))

#     # print custom response
#     if(pred.item()==1):
#         print("Positive review detected!")
#     else:
#         print("Negative review detected.")

In [ ]:
def predict(net, test_review, sequence_length=200):
    ''' Prints out whether a give review is predicted to be 
        positive or negative in sentiment, using a trained model.

        params:
        net - A trained net 
        test_review - a review made of normal text and punctuation
        sequence_length - the padded length of a review
        '''
    net.eval()

    # First preprocess the text 
    review = tokenize(test_review)
    seq_length = sequence_length
    features = pad_features(review, seq_length)
    
    # Convert numpy array into tensor
    features_tensor = torch.from_numpy(features)
    
    # batch size
    batch_size = features_tensor.shape[0]
    
    # Intialize the hidden state
    hidden = net.init_hidden(batch_size)
    
    # Lets move on GPU
    if train_on_gpu:
        features_tensor = features_tensor.cuda()
        
    # Get the output from the model
    output, hidden = net(features_tensor, hidden)
    
    # convert output probabilities to predicted class (0 or 1)
    pred = torch.round(output.squeeze())
    
    # printing output value, before rounding
    print('Prediction value, pre-rounding: {:.6f}'.format(output.item()))
    
    # Print in response
    if pred.item() == 1:
        print("Positive review detected!")
    else:
        print("Negative review detected!")
    
    
    
    # print custom response based on whether test_review is pos/neg
    



In [ ]:
# positive test review
test_review_pos = """one of the outstanding, excellent movies of hot Chocolate, hot Shot"""

In [ ]:
test_review_neg = "I hate this moive"

In [ ]:
# call function
# try negative and positive reviews!
seq_length=200  # Good to use training sequence
predict(net, test_review_neg, seq_length)

Prediction value, pre-rounding: 0.282652
Negative review detected!
